- package.json
- src/wallet.ts
- yarn.lock
**This PR adds the `estimateSize` function used to estimate the amount of fee in `wallet.ts`**
- `estimateSize` takes the number of inputs + the number of outputs in arguments. Depending of these data, it returns the (size in bytes) of the future transaction. I've taken 1100 bytes for confidential outputs + 149 bytes for an input.
- the `buildTx` function takes a `satPerBytes` optional parameter (default = 0.1) in order to compute the fee amount according to the estimated size.
@tiero @altafan please review
it closes #1
> fee estimation in wallet.ts

- package.json
- src/wallet.ts
- test/fixtures/wallet.keys.ts
- test/wallet.test.ts
- yarn.lock
**This PR proposes a refacto for `FetchAndUnblindUtxos` function**
TL;DR
- `FetchAndUnblindUtxos` now accepts an array of `AddressWithBlindingKey` as arguments
- `FetchAndUnblindUtxosGenerator` implements a javascript generator to optimize the way we fetch  and unblind the utxos
- _Unblinding_ step is now a nonblocking step. The idea is to return the original utxos if the unblind step fails (thus, the function handles unconfidential utxos)
- `BlindingKeyGetter` is a new type defining a function `string => string | undefined`
- `FetchAndUnblindTxs` returns all the txs for a list of addresses, and unblind them using a `BlindingKeyGetter`
- `FetchAndUnblindTxsGenerator` implements a js generator to optimize the way we fetch and unblind the transactions.
**I want all the utxos for a given …
> refactor the way we fetch and unblind utxos

- src/identity/identity.ts
- src/identity/masterpubkey.ts
- src/identity/mnemonic.ts
- src/identity/privatekey.ts
- src/utils.ts
- src/wallet.ts
- test/mnemonic.identity.test.ts
- test/transaction.test.ts
**This PR adds `blindPset` to `IdentityInterface` and his implementations in `MasterPubKey`, `Mnemonic` and `PrivateKey`**
- `blindPset` accepts 4 arguments: (1) the pset base64 encoded to blind, (2) an array specifying the ouputs indexes to blind, (3) outputs public keys map (output index --> hex encoded pub key) and (4) inputs private blinding keys map (input index --> hex encoded private key).
- arguments (3) & (4) are optional. The `blindPset` fetches _wallet blinding keys_ using the Identity instance **if** **the blinding key is not specified in (3) & (4)**. The idea is to provide only the non-wallet blinding keys.
- the implementations for `MasterPubKey`, `Mnemonic` and `PrivateKey` are exactly the same, except the `getBlindingKeys` strategy: that's why a more abstract method is …
> add the blindPset method to IdentityInterface

- src/transaction.ts
- yarn.lock
Update to last liquidjs-lib version + drop `networkFromAddress` function and use `getnetwork`.
@tiero @altafan please review
> update to liquidjs last version + drop networkFromAddress util function

- src/explorer/esplora.ts
This exports all the methods for unblinding an output of the explorer module.
This closes #19.
Please @tiero @louisinger review this.
> Export unblinding methods

- src/transaction.ts
- src/utils.ts
- test/_regtest.ts
- test/transaction.test.ts
This introduces changes to fix #22. By doing so I tried to simplify the code which I found a bit overcomplicated.
This also fixes the regtest test utils in order to remove all those time sleep.
Closes #22.
Closes #18.
Please @tiero @louisinger review this.
NOTE: I didn't add the broadcasting of all the tx created in transaction.test.ts because it somehow affects the result of other unit tests. We'll possibly fix this in another PR.
> Fix buildTx bug 

- src/explorer/esplora.ts
- test/esplora.test.ts
- yarn.lock
Allow to specify an optional `skip` method in `fetchAndUnblindUtxos` functions. Type of `skip` is `(utxo: UtxoInterface) => boolean`. If skip returns true, then the fetched utxo won't be unblinded.
> add skip method in fetchAndUnblindGenerator function

- src/explorer/esplora.ts
- test/esplora.test.ts
Similar to #31 except that the skip argument in FetchAndUnblinsTxs SKIP the **fetch and the unblinding step**. It means that the skipped transactions won't be returned by the generator.
> add skip function argument in FetchAndUnblindTxs

- src/explorer/esplora.ts
- test/esplora.test.ts
iterate even if the txid has been fetched in `FetchAndUnblindTxsGenerator` + add edge test case in `esplora.test.ts`.
> hotfix + edge test case fetchAndUnblindTxs

- src/explorer/esplora.ts
- test/esplora.test.ts
- test/fixtures/wallet.keys.ts
- yarn.lock
**issue**: if an address has unconfidential utxo, fetchAndUnblindUtxos will return utxos without prevouts. This causing `buildTx` to throw an error later.
**Fix**
- `tryToUnblindUtxo` becomes `FetchPrevoutAndTryToUnblindUtxo` ---> it sets prevout for ALL utxo and then try to unblind only confidential utxos.
- `unblindUtxo` throws an error if `prevout` is not set.
- add test case for unconfidential utxo.
> Support unconfidential utxo 

- src/identity/masterpubkey.ts
- src/identity/mnemonic.ts
- test/masterpubkey.identity.test.ts
- test/mnemonic.identity.test.ts
**This PR removes derivationPath member in `AddressInterfaceExtended` and implements MasterPubKey as super-class of Mnemonic.**
- Mnemonic signature becomes  `Mnemonic extends MasterPublicKey implements IdentityInterface` -> it avoids copy/paste each time we need to modify something in MasterPubKey/Mnemonic.
- backward compatible (does not break the current tests).
it closes #41 
@tiero @Janaka-Steph please review
> Mnemonic extends MasterPubKey

- src/explorer/esplora.ts
- src/types.ts
- test/esplora.test.ts
This PR adds blinders to TxInterface outputs, export a new function `FetchTx` and a `makeUnblindURL` function.
- `makeUnblindUrl` can be used to create explorer's URL with query string containing blinding data. `getUnblindUrlFromTx` makes the same thing using a `TxInterface` as an argument.
- `FetchTx` uses esplora to get a `TxInterface` using a Tx ID.
> fetchTx and makeUnblindUrl functions

- src/explorer/esplora.ts
- src/explorer/transaction.ts
- src/explorer/utxos.ts
- src/index.ts
- src/utils.ts
- src/wallet.ts
- test/transaction.test.ts
- test/wallet.test.ts
This PR proposes a hotfix in order to "skip" if a transaction can't be unblinded. This lets to ignore "malware" transactions and so don't break tdex-app.
> [HOTFIX] log unblind errors in fetchAndAndUnblindTxsGenerator instead of throw

- src/identity/masterpubkey.ts
- src/identity/mnemonic.ts
- test/mnemonic.identity.test.ts
This PR adds a check used in `blindPset` in order to throw an error if we try to blind a non-wallet output (only if we do not specify the blinding key) + unit test
> Add checkScript optional parameter in masterPubkey.getBlindingKeyPair method

- src/explorer/esplora.ts
This PR adds two fixes in the `getUnblindURLFromTx` function:
1. does not include fee output 
2. reverse blinders bytes in the URL
tested :heavy_check_mark: 
example: https://blockstream.info/liquid/tx/1889bca2cfb8bfb13d48f96b71bf714a9a4030a42865a3de7ee4ef6e896fb0ba#blinded=48228827,ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2,17683bbed29ea7e4b74f7b82165e9e7490d434eb7995c5e0a1bec0e33bc9e8d8,8bbba8c055e5555d0c4c6226167dbf13562304d71b4549ce10505dfbea2ec087
> Fix unblind URL builder

- package.json
- src/identity/browserinject.ts
- src/identity/identity.ts
- yarn.lock
This adds a new `BrowserInject` identity of type `Inject` to the ldk project.
To do that, the IdentityInterface had been updated where some methods can return also a Promise, to allow the async nature of Browser extension and in the future of hardware wallets﻿. 
**NOTICE** the internal `provider` property of `BrowserInject` class is of type `MarinaProvider` for the reason that there aren't other TypeScript spec out there (yet) and alos we need to be sure we have those specific methods injected in the DOM to satisfy our internal Interface requirements.
> Add BrowserInject identity type and add Promise return type to IdentityInterface methods

- src/identity/identity.ts
- src/identity/masterpubkey.ts
- src/identity/mnemonic.ts
- src/identity/privatekey.ts
- test/esplora.test.ts
- test/fixtures/wallet.keys.ts
- test/masterpubkey.identity.test.ts
- test/mnemonic.identity.test.ts
- test/privatekey.identity.test.ts
- test/transaction.test.ts
- test/wallet.test.ts
This PR simplifies the `IdentityInterface`: all the methods now return `Promises`. 
- Change the `IdentityInterface` declaration.
- Update all the "sync" implementation : `Mnemonic`, `PrivateKey` & `MasterPubKey`.
- Update all the tests (some needs to be async now).
it includes **breaking changes**.
> Identity interface returns promises

- src/explorer/utxos.ts
- test/esplora.test.ts
This PR aims to fix a set of bugs happening during the `fetchAndUnblindUtxos` unblinding step.
- `fetchAndUnblindUtxos` now run unblind tasks in sequence instead of as a set of promises.
-  now we check the relation between confidential address & blinding private key given as parameters.
- add a test case with an invalid address/blindPrivKey.
> improve fetchAndUnblindUtxos + add test for wrong private key

- src/types.ts
This adds 2 new props `redeemScript` and `witnessScript` to the `UtxoInterface` in order to support handling inputs of type P2SH or P2WSH. For these input types, the relative partial inputs require redeem or witness script to not be null.
Please @tiero review this
> Support P2SH/P2WSH utxos

- src/error/unblind-error.ts
- src/explorer/transaction.ts
- src/explorer/utxos.ts
- test/esplora.test.ts
- test/wallet.test.ts
This PR add a ` try { } catch` statement in `fetchAndUnblindTxsGenerator` and `fetchAndUnblindUtxosGenerator`. It aims to ignore unblinding errors (via `UnblindError` object).
Breaking change for `fetchPrevoutAndTryToUnblindUtxo` function.
it closes #56
> [fix] catch and return unblindErrors if any unblinding step has failed

- src/identity/masterpubkey.ts
generate addresses in batches of 20 (GAP_LIMIT) to ensure that all addresses are tested.
> [hotfix] Mnemonic restoration

- src/identity/browserinject.ts
- src/restorer/mnemonic-restorer.ts
- test/mnemonic.identity.test.ts
Fix bug where it generates addresses 0/0 and 1/0 even when seed is new.
It closes #64 
Make StateRestorerOpts properties optional for the case where seed is new and no addresses have been found.
Please review @tiero @louisinger
> Prevent generating addresses if none has been used

- src/restorer/mnemonic-restorer.ts
- test/mnemonic.identity.test.ts
**This PR uses `Promise.all` at every steps in restorers. It lets to reduce a lot the time to restore wallet's addresses.**
this is not a breaking change.
it closes #68 
> Optimize restorers

- src/explorer/esplora.ts
Check that transaction input is not a pegin to prevent fetching mainchain pegin tx from Liquid Esplora.
Please review @tiero @louisinger
> Don't fetch mainchain pegin tx from Liquid Esplora

- src/explorer/esplora.ts
- src/types.ts
**This PR is a hotfix for pegin transactions returned by generators.**
`InputInterface` is now returned in case of `is_pegin =true` in EsploraTx. 
it closes #74 
@Janaka-Steph please review
> hotfix pegin tx from esplora

- src/explorer/transaction.ts
Avoid `TypeError: Cannot use 'in' operator to search for 'surjectionProof' in undefined` on `isBlindedOutputInterface()` by checking if prevout is not undefined.
Please review @tiero @louisinger
> Check prevout is not undefined (in case of pegin)

- src/restorer/mnemonic-restorer.ts
restorerFromState works with all IdentityInterface so useful to export it in order to rewrite custom restorers in apps.
@tiero please review this
> export `restorerFromState` function

- src/coinselection/coinSelector.ts
- src/coinselection/greedy.ts
- src/coinselection/utils.ts
- src/transaction.ts
- src/types.ts
- src/wallet.ts
- test/esplora.test.ts
- test/fixtures/wallet.keys.ts
- test/transaction.test.ts
- test/wallet.test.ts
**This PR changes the `CoinSelector` type: adding a way to handle errors via `CoinSelectorErrorFn`.**
- move (and simplify) the coin selection logic from `greedy.ts` to `coinselection/utils.ts` file. 
- `CoinSelectorErrorFn` defines a function launched in case of "not enough fund error" in coin selection. 
- update `wallet.buildTx` according to new error handling function.
It lets to specify the behavior of the coin selector if the utxos can't fund the array of recipients. Instead of throw an error, we can handle the error according to specific needs (like[ subtract fee amount scenario](https://github.com/vulpemventures/marina/issues/93) - see `sendTx`). 
- add `sendTx` method to `WalletInterface`: this function can be used to create a **withdraw transaction** (= a single recipient tx): a …
> Custom error handling in CoinSelector (substract fee scenario) + `sendTx` in wallet

- src/explorer/utxos.ts
fix bad compare function `compareVin` using to sort the list of txs in `utxosFromTransactions`: should return -1 in case of vin does not include the `b.txid`.
> hotfix compareVin function

- src/coinselection/utils.ts
Value must be a number, coerce it into number if is not.
Throw error if at the end is still not a number.
> Sanitize recipient.value on function reduceRecipients

- .github/workflows/main.yml
- package.json
- src/bip32.ts
- src/identity/browserinject.ts
- src/identity/identity.ts
- src/identity/masterpubkey.ts
- src/identity/mnemonic.ts
- src/identity/multisig.ts
- src/identity/multisigWatchOnly.ts
- src/identity/privatekey.ts
- src/index.ts
- src/p2ms.ts
- src/transaction.ts
- src/utils.ts
- src/wallet.ts
- test/mnemonic.identity.test.ts
- test/multisig.identity.test.ts
- test/privatekey.identity.test.ts
- test/transaction.test.ts
- test/utils.test.ts
- yarn.lock
bump to liquidjs 6.0.1
* several deps are introduced (mainly because removed in liquidjs-lib): ecpair, tiny-secp256k1.
* bip32.ts instances a new BIP32API (it comes from new version of bip32)
* LDK exports liquidjs's `AssetHash` util
* some update on liquidjs type imports (due to bitcoinjs merge)
> bump liquidjs 6.0.1

- package.json
- src/ecpair.ts
- src/explorer/utxos.ts
- src/identity/mnemonic.ts
- src/identity/multisig.ts
- src/identity/privatekey.ts
- src/index.ts
- test/esplora.test.ts
- test/fixtures/wallet.keys.ts
- test/privatekey.identity.test.ts
- yarn.lock
* bumps liquidjs-lib to 6.0.2-liquid.0
* creates and exports `ecpair.ts`
* updates import of ECPair
> bump liquidjs-lib to 6.0.2-liquid.0

- package.json
- src/bip32.ts
- src/ecclib.ts
- src/ecpair.ts
- src/identity/identity.ts
- src/index.ts
- src/slip77.ts
- test/mnemonic.identity.test.ts
- test/multisig.identity.test.ts
- test/privatekey.identity.test.ts
- yarn.lock
This PR updates LDK with the new changes of liquidjs-lib.
* create a new `ecclib` file: this is basically the `TinySecp256k1Interface` used by "injected libs" (bip32, slip77, bip341...)
* re-export `ecc` from `ecclib` -> the idea is to let the user re-use the **LDK version of tiny-secp256k1** if needed.
* re-export all from `liquidjs-lib`: it closes #66 
* updates some Psbt methods in tests in order to fix the new liquidjs breaking changes.
---
The idea is to simplify the "import process" because we often use liquidjs + LDK. Moreover, the new 'injected logic' for ecc lib could complexify the thing. With the PR changes, importing **only ldk in a project let you**:
* do not manage ecclib injection in bip32 & slip77
* access all the LDK methods
* access all the liquidjs methods and classes …
> Bump liquidjs-lib to `6.0.2-liquid.1`

- package.json
- src/identity/browserinject.ts
- src/identity/masterpubkey.ts
- src/identity/multisigWatchOnly.ts
- src/restorer/mnemonic-restorer.ts
- src/types.ts
- yarn.lock
**no breaking changes**
- bumps to latest liquidjs-lib `6.0.2-liquid.5` (fix taproot pset).
- remove `marina-provider` dep, the type `MarinaProvider` has been replaced by a new `BrowserInjectProviderInterface`.
- extend `AddressInterface` type & export explora restorer function from `restorer.ts` (let to extend IdentityInterface in upper projects).
> liquidjs `6.0.2-liquid.5` update

- package.json
- src/bip32.ts
- src/ecclib.ts
- src/ecpair.ts
- src/explorer/utxos.ts
- src/identity/identity.ts
- src/identity/masterpubkey.ts
- src/identity/mnemonic.ts
- src/identity/multisig.ts
- src/identity/multisigWatchOnly.ts
- src/identity/privatekey.ts
- src/index.ts
- src/p2ms.ts
- src/slip77.ts
- src/utils.ts
- src/wallet.ts
- test/esplora.test.ts
- test/fixtures/wallet.keys.ts
- test/masterpubkey.identity.test.ts
- test/mnemonic.identity.test.ts
- test/multisig.identity.test.ts
- test/multisigwatchonly.identity.test.ts
- test/privatekey.identity.test.ts
- test/transaction.test.ts
- test/utils.test.ts
- yarn.lock
**This PR removes the `tiny-secp256k1` dependencie.** 
- some util functions and `Identity` class need to inject `TinySecp256k1Interface` (exported from identity.ts).
- rewrite xpub/blindind keys check functions using regular expressions instead of ecc.
- do not export anymore the injected bip32, slip77 and ecpair lib.
> injectable tiny-secp256k1 lib

- test/utils.test.ts
This PR adds a constant test vector for `blindingKeyFromXPbubs` function.
_There are no official tests at the moment, this test is mainly to ensure that other libraries are compatible with LDK._
cc/ @sekulicd @tiero
> (multisig)masterBlindingKey from xpubs: add a test vector

- src/descriptors/ast.ts
- src/descriptors/doc.md
- src/descriptors/index.ts
- src/descriptors/parser.ts
- src/descriptors/preprocessing.ts
- src/descriptors/utils.ts
- src/index.ts
- src/script-analyser.ts
- test/descriptors.spec.ts
- test/script-analyser.spec.ts
This PR adds some code from https://github.com/vulpemventures/marina/pull/345 to LDK
- `descriptors` module using to parse descriptor-like string templates -> need the "injected ecclib pattern" (new change from marina)
- `script-analyzer.ts` lets to check a script or a tapscript tree and extract some useful data to "unlock" the script.
- 2 tests files from marina PR
> add descriptors module + script-analyzer.ts

- src/explorer/transaction.ts
- src/transaction.ts
- src/wallet.ts
- test/transaction.test.ts
it closes #118 
let the singleRecipient pset created by WalletInterface function support several change addresses.
> `changeGetter` in craftSingleRecipient function

- src/blinding.ts
- src/index.ts
This PR adds two functions [coming from marina](https://github.com/vulpemventures/marina/blob/master/src/application/utils/transaction.ts#L35-L77) allowing the creation of blinding maps (parameters in blindOutputs* functions) from a set of coins (inputs map) and confidential addresses (outputs map).
- `inputBlindingDataMap` set up the unblind data of coins associated with the pset inputs.
- `outputBlindingPubkeysMap` get the blinding public keys from addresses (if confidential ones) associated with the pset outputs.
> add `blinding.ts` utility file

- src/descriptors/index.ts
- src/descriptors/parser.ts
- src/descriptors/preprocessing.ts
- test/descriptors.spec.ts
* eltr($test, { asm(OP_FALSE) }) is now parsable in descriptors
* several fixes about namespaces: now can include the following special char "@", ".", "_" or "-". So $marina@v0 is now a valid namespace.
> Descriptor: single-leaf eltr tree parsing 

- src/identity/mnemonic.ts
- src/identity/multisig.ts
- src/identity/multisigWatchOnly.ts
- src/types.ts
This change is being made towards the goal of enabling the usage of passphrases for wallet restoration in marina as per https://github.com/vulpemventures/marina/issues/278
> Changed Mnemonic, MultisigWatchOnly, and Multisig to use the passphrase in seed generation

- src/identity/masterpubkey.ts
- src/identity/mnemonic.ts
- test/masterpubkey.identity.test.ts
- test/mnemonic.identity.test.ts
This PR changes the masterPublicKey of MasterPublicKey (and Mnemonic)
* instead of returning `baseNode.publicKey` as masterPublicKey, return the neutered version of baseNode `baseNode.neutered`.
* _same keys and addresses are generated_, only the masterPublicKey returned by Mnemonic and MasterPublicKey identites are different.
* neutered master extended key **is** the master xpub of the bip32 node
small fix related to baseDerivation path: it closes #127 
EDIT: the PR does not modify Multisig identities xpubs
@tiero @sekulicd please review
> MasterPublicKey xpub = neutered extended public key

- src/explorer/api.ts
- src/explorer/chainsync.ts
- src/explorer/transaction.ts
- src/explorer/utxos.ts
- src/identity/identity.ts
- src/index.ts
- src/restorer/chainsync.ts
- src/restorer/mnemonic-restorer.ts
- src/types.ts
- test/updaters.test.ts
This PR proposes a rework of updaters generators (`fetchAndUnblindUtxos` & `fetchAndUnblindTxs` are still exported)
* `fetchAllUtxos`, `fetchAllTxs` are the new "fetch" functions (+ the equivalent "generators" functions). They accept a list of addresses (as string) and handle blinding private key via `BlindKeyGetterAsync` function.
* To request the explorer, the http calls are abstracted into a new `ChainAPI` interface.
* `Electrs` class is the regular electrs ChainAPI implementation.
* `ElectrsBatchServer` extends `Electrs` with a batch-server proxy optimizing /txs and /utxo requests.
* `privateBlindKeyGetter` is an util function using to create a `BlindKeyGetter` from any `IdentityInterface`
* `makeRestorerFromChainAPI` is a factory function letting to create `Restorer` powered by …
> `ChainAPI` interface + electrs batch server support

- src/explorer/api.ts
- src/explorer/chainsync.ts
* `esploraTxToTxInterface` internal function in `ChainAPI` implementation is extremly expensive. In order to improve this, I've moved the `skip` parameters from generators to ChainAPI methods. Thus, it lets to **do not call /hex endpoints** if skip(x) returns true.
* `ElectrsBatchServer` uses new `txids/transactions/hex` endpoint from https://github.com/vulpemventures/electrs-batch-server/pull/1.
* `ChainAPI` interface defines a new method: `FetchTxsHex`.
this branch can be tested on the following marina PR: https://github.com/vulpemventures/marina/pull/392
> add `skip` function in ChainAPI + use /hex endpoint in `ElectrsBatchServer`

- src/explorer/api.ts
- src/explorer/transaction.ts
This PR fixes the `unblindTransaction` function (exported & used by updaters). The function skipped the prevouts unblinding due to bad use of `isConfidentialOutput` <- passing the prevout there fix it.
BONUS: fix #136 
@tiero @Janaka-Steph please review
> [HOTFIX] UnblindTransaction

- src/transaction.ts
* `estimateTxSize` now accept `numConfidentialOutputs` and `numConfidentialInputs`
* update estimateTxSize everywhere (Wallet.sendTx, craft*Pset functions...)
it closes #135 
@tiero @altafan  please review
> Improve transaction vsize estimation
